#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.5
# In conjunction with Tcl version 8.6
#    Feb 21, 2016 02:31:01 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import rbgui1_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('New_Toplevel_1')
    geom = "702x368+386+325"
    root.geometry(geom)
    rbgui1_support.set_Tk_var()
    w = New_Toplevel_1 (root)
    rbgui1_support.init(root, w)
    root.mainloop()

w = None
def create_New_Toplevel_1(root, param=None):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    w.title('New_Toplevel_1')
    geom = "702x368+386+325"
    rbgui1_support.set_Tk_var()
    w.geometry(geom)
    w_win = New_Toplevel_1 (w)
    rbgui1_support.init(w, w_win, param)
    return w_win

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class New_Toplevel_1:
    def __init__(self, master=None):
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Courier New} -size 9 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        font12 = "-family Tahoma -size 9 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])
        master.configure(background="#d9d9d9")
        master.configure(highlightbackground="#d9d9d9")
        master.configure(highlightcolor="black")


        self.TLabelframe1 = ttk.Labelframe(master)
        self.TLabelframe1.place(relx=0.01, rely=0.03, relheight=0.2
                , relwidth=0.17)
        self.TLabelframe1.configure(text='''Serial connect''')
        self.TLabelframe1.configure(width=120)

        self.btn_connect = Button(self.TLabelframe1)
        self.btn_connect.place(relx=0.08, rely=0.21, height=22, width=65)
        self.btn_connect.configure(activebackground="#d9d9d9")
        self.btn_connect.configure(activeforeground="#000000")
        self.btn_connect.configure(background=_bgcolor)
        self.btn_connect.configure(command=rbgui1_support.do_connect_serial)
        self.btn_connect.configure(disabledforeground="#a3a3a3")
        self.btn_connect.configure(foreground="#000000")
        self.btn_connect.configure(highlightbackground="#d9d9d9")
        self.btn_connect.configure(highlightcolor="black")
        self.btn_connect.configure(pady="0")
        self.btn_connect.configure(text='''Connect''')

        self.txt_connect_indicator = Entry(self.TLabelframe1)
        self.txt_connect_indicator.place(relx=0.67, rely=0.27, relheight=0.25
                , relwidth=0.2)
        self.txt_connect_indicator.configure(background="white")
        self.txt_connect_indicator.configure(disabledforeground="#a3a3a3")
        self.txt_connect_indicator.configure(font="TkFixedFont")
        self.txt_connect_indicator.configure(foreground="#000000")
        self.txt_connect_indicator.configure(highlightbackground="#d9d9d9")
        self.txt_connect_indicator.configure(highlightcolor="black")
        self.txt_connect_indicator.configure(insertbackground="black")
        self.txt_connect_indicator.configure(selectbackground="#c4c4c4")
        self.txt_connect_indicator.configure(selectforeground="black")

        self.chk_Allow_motion = Checkbutton(self.TLabelframe1)
        self.chk_Allow_motion.place(relx=0.08, rely=0.67, relheight=0.29
                , relwidth=0.81)
        self.chk_Allow_motion.configure(activebackground="#d9d9d9")
        self.chk_Allow_motion.configure(activeforeground="#000000")
        self.chk_Allow_motion.configure(background=_bgcolor)
        self.chk_Allow_motion.configure(command=rbgui1_support.HandleForceToken)
        self.chk_Allow_motion.configure(disabledforeground="#a3a3a3")
        self.chk_Allow_motion.configure(foreground="#000000")
        self.chk_Allow_motion.configure(highlightbackground="#d9d9d9")
        self.chk_Allow_motion.configure(highlightcolor="black")
        self.chk_Allow_motion.configure(justify=LEFT)
        self.chk_Allow_motion.configure(text='''Allow Motion''')
        self.chk_Allow_motion.configure(variable=rbgui1_support.wvar.Force_Token_var)

        self.menubar = Menu(master,bg=_bgcolor,fg=_fgcolor)
        master.configure(menu = self.menubar)

        self.file = Menu(master,tearoff=0)
        self.menubar.add_cascade(menu=self.file,
                activebackground="#d9d9d9",
                activeforeground="#111111",
                accelerator="f",
                background="#d9d9d9",
                foreground="#000000",
                label="File")
        self.file.add_command(
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                foreground="#000000",
                label="Exit")
        self.settings = Menu(master,tearoff=0)
        self.menubar.add_cascade(menu=self.settings,
                activebackground="#d9d9d9",
                activeforeground="#111111",
                background="#d9d9d9",
                foreground="#000000",
                label="Settings")
        self.settings.add_command(
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=rbgui1_support.do_SerialPortConfig,
                foreground="#000000",
                label="Config Serial port")
        self.about = Menu(master,tearoff=0)
        self.menubar.add_cascade(menu=self.about,
                activebackground="#d9d9d9",
                activeforeground="#111111",
                accelerator="a",
                background="#d9d9d9",
                foreground="#000000",
                label="About")
        self.about.add_command(
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=rbgui1_support.do_about,
                foreground="#000000",
                label="Show About")


        self.TLabelframe2 = ttk.Labelframe(master)
        self.TLabelframe2.place(relx=0.01, rely=0.24, relheight=0.5
                , relwidth=0.36)
        self.TLabelframe2.configure(text='''Manual controls''')
        self.TLabelframe2.configure(width=250)

        self.ts_direction = ttk.Scale(self.TLabelframe2)
        self.ts_direction.place(relx=0.4, rely=0.54, relwidth=0.4, relheight=0.0
                , height=16)
        self.ts_direction.configure(command=rbgui1_support.do_new_direction)
        self.ts_direction.configure(variable=rbgui1_support.wvar.ts_direction_value)
        self.ts_direction.configure(from_="50")
        self.ts_direction.configure(to="-50")
        self.ts_direction.configure(takefocus="")

        self.Label1 = Label(self.TLabelframe2)
        self.Label1.place(relx=0.48, rely=0.43, height=19, width=48)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background=_bgcolor)
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Direction''')

        self.entry_setdirection = Entry(self.TLabelframe2)
        self.entry_setdirection.place(relx=0.6, rely=0.65, relheight=0.1
                , relwidth=0.26)
        self.entry_setdirection.configure(background="white")
        self.entry_setdirection.configure(disabledforeground="#a3a3a3")
        self.entry_setdirection.configure(font="TkFixedFont")
        self.entry_setdirection.configure(foreground="#000000")
        self.entry_setdirection.configure(highlightbackground="#d9d9d9")
        self.entry_setdirection.configure(highlightcolor="black")
        self.entry_setdirection.configure(insertbackground="black")
        self.entry_setdirection.configure(justify=RIGHT)
        self.entry_setdirection.configure(selectbackground="#c4c4c4")
        self.entry_setdirection.configure(selectforeground="black")
        self.entry_setdirection.configure(textvariable=rbgui1_support.wvar.gui_set_direction)

        self.entry_actdirection = Entry(self.TLabelframe2)
        self.entry_actdirection.place(relx=0.6, rely=0.76, relheight=0.1
                , relwidth=0.26)
        self.entry_actdirection.configure(background="white")
        self.entry_actdirection.configure(disabledforeground="#a3a3a3")
        self.entry_actdirection.configure(font="TkFixedFont")
        self.entry_actdirection.configure(foreground="#000000")
        self.entry_actdirection.configure(highlightbackground="#d9d9d9")
        self.entry_actdirection.configure(highlightcolor="black")
        self.entry_actdirection.configure(insertbackground="black")
        self.entry_actdirection.configure(justify=RIGHT)
        self.entry_actdirection.configure(selectbackground="#c4c4c4")
        self.entry_actdirection.configure(selectforeground="black")
        self.entry_actdirection.configure(textvariable=rbgui1_support.wvar.gui_act_direction)

        self.Label2 = Label(self.TLabelframe2)
        self.Label2.place(relx=0.4, rely=0.65, height=19, width=32)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background=_bgcolor)
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Set''')

        self.Label3 = Label(self.TLabelframe2)
        self.Label3.place(relx=0.4, rely=0.76, height=19, width=32)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background=_bgcolor)
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Act''')

        self.Label4 = Label(self.TLabelframe2)
        self.Label4.place(relx=0.04, rely=0.76, height=19, width=36)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background=_bgcolor)
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Speed''')

        self.entry_setspeed = Entry(self.TLabelframe2)
        self.entry_setspeed.place(relx=0.4, rely=0.05, relheight=0.1
                , relwidth=0.3)
        self.entry_setspeed.configure(background="white")
        self.entry_setspeed.configure(disabledforeground="#a3a3a3")
        self.entry_setspeed.configure(font=font10)
        self.entry_setspeed.configure(foreground="#000000")
        self.entry_setspeed.configure(highlightbackground="#d9d9d9")
        self.entry_setspeed.configure(highlightcolor="black")
        self.entry_setspeed.configure(insertbackground="black")
        self.entry_setspeed.configure(justify=RIGHT)
        self.entry_setspeed.configure(selectbackground="#c4c4c4")
        self.entry_setspeed.configure(selectforeground="black")
        self.entry_setspeed.configure(textvariable=rbgui1_support.wvar.gui_setspeed)

        self.Label5 = Label(self.TLabelframe2)
        self.Label5.place(relx=0.24, rely=0.05, height=19, width=32)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background=_bgcolor)
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Set''')

        self.entry_actspeed = Entry(self.TLabelframe2)
        self.entry_actspeed.place(relx=0.4, rely=0.16, relheight=0.1
                , relwidth=0.3)
        self.entry_actspeed.configure(background="white")
        self.entry_actspeed.configure(disabledforeground="#a3a3a3")
        self.entry_actspeed.configure(font="TkFixedFont")
        self.entry_actspeed.configure(foreground="#000000")
        self.entry_actspeed.configure(highlightbackground="#d9d9d9")
        self.entry_actspeed.configure(highlightcolor="black")
        self.entry_actspeed.configure(insertbackground="black")
        self.entry_actspeed.configure(justify=RIGHT)
        self.entry_actspeed.configure(selectbackground="#c4c4c4")
        self.entry_actspeed.configure(selectforeground="black")
        self.entry_actspeed.configure(textvariable=rbgui1_support.wvar.gui_actspeed)

        self.Label6 = Label(self.TLabelframe2)
        self.Label6.place(relx=0.22, rely=0.16, height=19, width=41)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background=_bgcolor)
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''Act''')

        self.Label7 = Label(self.TLabelframe2)
        self.Label7.place(relx=0.4, rely=0.86, height=19, width=47)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(background=_bgcolor)
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''Rad/sec''')
        self.Label7.configure(width=47)

        self.entry_radpersec = Entry(self.TLabelframe2)
        self.entry_radpersec.place(relx=0.6, rely=0.86, relheight=0.1, relwidth=0.26)
        self.entry_radpersec.configure(background="white")
        self.entry_radpersec.configure(disabledforeground="#a3a3a3")
        self.entry_radpersec.configure(font="TkFixedFont")
        self.entry_radpersec.configure(foreground="#000000")
        self.entry_radpersec.configure(highlightbackground="#d9d9d9")
        self.entry_radpersec.configure(highlightcolor="black")
        self.entry_radpersec.configure(insertbackground="black")
        self.entry_radpersec.configure(justify=RIGHT)
        self.entry_radpersec.configure(selectbackground="#c4c4c4")
        self.entry_radpersec.configure(selectforeground="black")
        self.entry_radpersec.configure(textvariable=rbgui1_support.wvar.gui_radpersec)

        self.ts_speed = Scale(self.TLabelframe2)
        self.ts_speed.place(relx=0.04, rely=0.11, relwidth=0.0, relheight=0.57
                , width=40)
        self.ts_speed.configure(activebackground="#d9d9d9")
        self.ts_speed.configure(background=_bgcolor)
        self.ts_speed.configure(command=rbgui1_support.do_new_speed)
        self.ts_speed.configure(font="TkTextFont")
        self.ts_speed.configure(foreground="#000000")
        self.ts_speed.configure(from_="50.0")
        self.ts_speed.configure(highlightbackground="#d9d9d9")
        self.ts_speed.configure(highlightcolor="black")
        self.ts_speed.configure(to="-50.0")
        self.ts_speed.configure(troughcolor="#d9d9d9")
        self.ts_speed.configure(variable=rbgui1_support.wvar.ts_speed_value)
        self.ts_speed.configure(width=12)

        self.btn_center = Button(self.TLabelframe2)
        self.btn_center.place(relx=0.76, rely=0.27, height=31, width=52)
        self.btn_center.configure(activebackground="#d9d9d9")
        self.btn_center.configure(activeforeground="#000000")
        self.btn_center.configure(background=_bgcolor)
        self.btn_center.configure(command=rbgui1_support.Do_Center)
        self.btn_center.configure(disabledforeground="#a3a3a3")
        self.btn_center.configure(font=font12)
        self.btn_center.configure(foreground="#000000")
        self.btn_center.configure(highlightbackground="#d9d9d9")
        self.btn_center.configure(highlightcolor="black")
        self.btn_center.configure(pady="0")
        self.btn_center.configure(text='''Center''')
        self.btn_center.configure(width=52)

        self.btn_Stop = Button(self.TLabelframe2)
        self.btn_Stop.place(relx=0.2, rely=0.7, height=31, width=51)
        self.btn_Stop.configure(activebackground="#d9d9d9")
        self.btn_Stop.configure(activeforeground="#000000")
        self.btn_Stop.configure(background=_bgcolor)
        self.btn_Stop.configure(command=rbgui1_support.Do_Stop)
        self.btn_Stop.configure(disabledforeground="#a3a3a3")
        self.btn_Stop.configure(font=font12)
        self.btn_Stop.configure(foreground="#000000")
        self.btn_Stop.configure(highlightbackground="#d9d9d9")
        self.btn_Stop.configure(highlightcolor="black")
        self.btn_Stop.configure(pady="0")
        self.btn_Stop.configure(text='''Stop''')
        self.btn_Stop.configure(width=51)

        self.Label11 = Label(self.TLabelframe2)
        self.Label11.place(relx=0.24, rely=0.27, height=19, width=35)
        self.Label11.configure(background=_bgcolor)
        self.Label11.configure(disabledforeground="#a3a3a3")
        self.Label11.configure(foreground="#000000")
        self.Label11.configure(text='''M/Sec''')

        self.entry_actspeed_mpers = Entry(self.TLabelframe2)
        self.entry_actspeed_mpers.place(relx=0.4, rely=0.29, relheight=0.1
                , relwidth=0.3)
        self.entry_actspeed_mpers.configure(background="white")
        self.entry_actspeed_mpers.configure(disabledforeground="#a3a3a3")
        self.entry_actspeed_mpers.configure(font="TkFixedFont")
        self.entry_actspeed_mpers.configure(foreground="#000000")
        self.entry_actspeed_mpers.configure(highlightbackground="#d9d9d9")
        self.entry_actspeed_mpers.configure(highlightcolor="black")
        self.entry_actspeed_mpers.configure(insertbackground="black")
        self.entry_actspeed_mpers.configure(justify=RIGHT)
        self.entry_actspeed_mpers.configure(selectbackground="#c4c4c4")
        self.entry_actspeed_mpers.configure(selectforeground="black")
        self.entry_actspeed_mpers.configure(textvariable=rbgui1_support.wvar.gui_actspeedmpersec)
        self.entry_actspeed_mpers.configure(width=74)

        self.lf_status = ttk.Labelframe(master)
        self.lf_status.place(relx=0.38, rely=0.0, relheight=0.75, relwidth=0.2)
        self.lf_status.configure(text='''Status''')
        self.lf_status.configure(width=140)

        self.entry_status = Entry(self.lf_status)
        self.entry_status.place(relx=0.07, rely=0.07, relheight=0.07
                , relwidth=0.46)
        self.entry_status.configure(background="white")
        self.entry_status.configure(disabledforeground="#a3a3a3")
        self.entry_status.configure(font="TkFixedFont")
        self.entry_status.configure(foreground="#000000")
        self.entry_status.configure(highlightbackground="#d9d9d9")
        self.entry_status.configure(highlightcolor="black")
        self.entry_status.configure(insertbackground="black")
        self.entry_status.configure(selectbackground="#c4c4c4")
        self.entry_status.configure(selectforeground="black")
        self.entry_status.configure(textvariable=rbgui1_support.wvar.gui_statushex)

        self.Cs3 = Checkbutton(self.lf_status)
        self.Cs3.place(relx=0.0, rely=0.27, relheight=0.08, relwidth=0.54)
        self.Cs3.configure(activebackground="#d9d9d9")
        self.Cs3.configure(activeforeground="#000000")
        self.Cs3.configure(anchor=W)
        self.Cs3.configure(background=_bgcolor)
        self.Cs3.configure(disabledforeground="#a3a3a3")
        self.Cs3.configure(foreground="#000000")
        self.Cs3.configure(highlightbackground="#d9d9d9")
        self.Cs3.configure(highlightcolor="black")
        self.Cs3.configure(justify=LEFT)
        self.Cs3.configure(text='''3 Enabled''')
        self.Cs3.configure(variable=rbgui1_support.wvar.Cs3var)

        self.Cs15 = Checkbutton(self.lf_status)
        self.Cs15.place(relx=0.0, rely=0.89, relheight=0.08, relwidth=0.5)
        self.Cs15.configure(activebackground="#d9d9d9")
        self.Cs15.configure(activeforeground="#000000")
        self.Cs15.configure(anchor=W)
        self.Cs15.configure(background=_bgcolor)
        self.Cs15.configure(disabledforeground="#a3a3a3")
        self.Cs15.configure(foreground="#000000")
        self.Cs15.configure(highlightbackground="#d9d9d9")
        self.Cs15.configure(highlightcolor="black")
        self.Cs15.configure(justify=LEFT)
        self.Cs15.configure(text='''15 Alarm''')
        self.Cs15.configure(variable=rbgui1_support.wvar.Cs15var)

        self.Cs4 = Checkbutton(self.lf_status)
        self.Cs4.place(relx=0.0, rely=0.35, relheight=0.08, relwidth=0.55)
        self.Cs4.configure(activebackground="#d9d9d9")
        self.Cs4.configure(activeforeground="#000000")
        self.Cs4.configure(anchor=W)
        self.Cs4.configure(background=_bgcolor)
        self.Cs4.configure(disabledforeground="#a3a3a3")
        self.Cs4.configure(foreground="#000000")
        self.Cs4.configure(highlightbackground="#d9d9d9")
        self.Cs4.configure(highlightcolor="black")
        self.Cs4.configure(justify=LEFT)
        self.Cs4.configure(text='''4 Moveing''')
        self.Cs4.configure(variable=rbgui1_support.wvar.Cs4var)

        self.Cs5 = Checkbutton(self.lf_status)
        self.Cs5.place(relx=0.0, rely=0.42, relheight=0.08, relwidth=0.59)
        self.Cs5.configure(activebackground="#d9d9d9")
        self.Cs5.configure(activeforeground="#000000")
        self.Cs5.configure(anchor=W)
        self.Cs5.configure(background=_bgcolor)
        self.Cs5.configure(disabledforeground="#a3a3a3")
        self.Cs5.configure(foreground="#000000")
        self.Cs5.configure(highlightbackground="#d9d9d9")
        self.Cs5.configure(highlightcolor="black")
        self.Cs5.configure(justify=LEFT)
        self.Cs5.configure(text='''5 PC active''')
        self.Cs5.configure(variable=rbgui1_support.wvar.Cs5var)

        self.Cs7 = Checkbutton(self.lf_status)
        self.Cs7.place(relx=0.0, rely=0.49, relheight=0.08, relwidth=0.79)
        self.Cs7.configure(activebackground="#d9d9d9")
        self.Cs7.configure(activeforeground="#000000")
        self.Cs7.configure(anchor=W)
        self.Cs7.configure(background=_bgcolor)
        self.Cs7.configure(disabledforeground="#a3a3a3")
        self.Cs7.configure(foreground="#000000")
        self.Cs7.configure(highlightbackground="#d9d9d9")
        self.Cs7.configure(highlightcolor="black")
        self.Cs7.configure(justify=LEFT)
        self.Cs7.configure(text='''7 Joy stick active''')
        self.Cs7.configure(variable=rbgui1_support.wvar.Cs7var)

        self.Cs11 = Checkbutton(self.lf_status)
        self.Cs11.place(relx=0.0, rely=0.56, relheight=0.08, relwidth=0.76)
        self.Cs11.configure(activebackground="#d9d9d9")
        self.Cs11.configure(activeforeground="#000000")
        self.Cs11.configure(anchor=W)
        self.Cs11.configure(background=_bgcolor)
        self.Cs11.configure(disabledforeground="#a3a3a3")
        self.Cs11.configure(foreground="#000000")
        self.Cs11.configure(highlightbackground="#d9d9d9")
        self.Cs11.configure(highlightcolor="black")
        self.Cs11.configure(justify=LEFT)
        self.Cs11.configure(text='''11 Current error''')
        self.Cs11.configure(variable=rbgui1_support.wvar.Cs11var)

        self.Cs13 = Checkbutton(self.lf_status)
        self.Cs13.place(relx=0.0, rely=0.64, relheight=0.08, relwidth=0.68)
        self.Cs13.configure(activebackground="#d9d9d9")
        self.Cs13.configure(activeforeground="#000000")
        self.Cs13.configure(anchor=W)
        self.Cs13.configure(background=_bgcolor)
        self.Cs13.configure(disabledforeground="#a3a3a3")
        self.Cs13.configure(foreground="#000000")
        self.Cs13.configure(highlightbackground="#d9d9d9")
        self.Cs13.configure(highlightcolor="black")
        self.Cs13.configure(justify=LEFT)
        self.Cs13.configure(text='''13 Vin too low''')
        self.Cs13.configure(variable=rbgui1_support.wvar.Cs13var)

        self.Cs14 = Checkbutton(self.lf_status)
        self.Cs14.place(relx=0.0, rely=0.71, relheight=0.08, relwidth=0.74)
        self.Cs14.configure(activebackground="#d9d9d9")
        self.Cs14.configure(activeforeground="#000000")
        self.Cs14.configure(anchor=W)
        self.Cs14.configure(background=_bgcolor)
        self.Cs14.configure(disabledforeground="#a3a3a3")
        self.Cs14.configure(foreground="#000000")
        self.Cs14.configure(highlightbackground="#d9d9d9")
        self.Cs14.configure(highlightcolor="black")
        self.Cs14.configure(justify=LEFT)
        self.Cs14.configure(text='''14 3.3V too low''')
        self.Cs14.configure(variable=rbgui1_support.wvar.Cs14var)

        self.Cs0 = Checkbutton(self.lf_status)
        self.Cs0.place(relx=0.0, rely=0.2, relheight=0.08, relwidth=0.61)
        self.Cs0.configure(activebackground="#d9d9d9")
        self.Cs0.configure(activeforeground="#000000")
        self.Cs0.configure(anchor=W)
        self.Cs0.configure(background=_bgcolor)
        self.Cs0.configure(disabledforeground="#a3a3a3")
        self.Cs0.configure(foreground="#000000")
        self.Cs0.configure(highlightbackground="#d9d9d9")
        self.Cs0.configure(highlightcolor="black")
        self.Cs0.configure(justify=LEFT)
        self.Cs0.configure(text='''0 Watchdog''')
        self.Cs0.configure(variable=rbgui1_support.wvar.Cs0var)

        self.lf_voltages = LabelFrame(master)
        self.lf_voltages.place(relx=0.6, rely=0.0, relheight=0.75, relwidth=0.38)

        self.lf_voltages.configure(relief=GROOVE)
        self.lf_voltages.configure(foreground="black")
        self.lf_voltages.configure(text='''Voltage/Currents''')
        self.lf_voltages.configure(background=_bgcolor)
        self.lf_voltages.configure(highlightbackground="#d9d9d9")
        self.lf_voltages.configure(highlightcolor="black")
        self.lf_voltages.configure(width=270)

        self.lb_adc = Listbox(self.lf_voltages)
        self.lb_adc.place(relx=0.04, rely=0.07, relheight=0.78, relwidth=0.94)
        self.lb_adc.configure(background="white")
        self.lb_adc.configure(disabledforeground="#a3a3a3")
        self.lb_adc.configure(font="TkFixedFont")
        self.lb_adc.configure(foreground="#000000")
        self.lb_adc.configure(highlightbackground="#d9d9d9")
        self.lb_adc.configure(highlightcolor="black")
        self.lb_adc.configure(selectbackground="#c4c4c4")
        self.lb_adc.configure(selectforeground="black")

        self.btn_resetminmax = Button(self.lf_voltages)
        self.btn_resetminmax.place(relx=0.07, rely=0.87, height=21, width=121)
        self.btn_resetminmax.configure(activebackground="#d9d9d9")
        self.btn_resetminmax.configure(activeforeground="#000000")
        self.btn_resetminmax.configure(background=_bgcolor)
        self.btn_resetminmax.configure(command=rbgui1_support.do_resetminmax)
        self.btn_resetminmax.configure(disabledforeground="#a3a3a3")
        self.btn_resetminmax.configure(foreground="#000000")
        self.btn_resetminmax.configure(highlightbackground="#d9d9d9")
        self.btn_resetminmax.configure(highlightcolor="black")
        self.btn_resetminmax.configure(pady="0")
        self.btn_resetminmax.configure(text='''Reset Min Max''')

        self.Labelframe2 = LabelFrame(master)
        self.Labelframe2.place(relx=0.2, rely=0.03, relheight=0.2, relwidth=0.17)

        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(text='''Enable/Reset''')
        self.Labelframe2.configure(background=_bgcolor)
        self.Labelframe2.configure(highlightbackground="#d9d9d9")
        self.Labelframe2.configure(highlightcolor="black")
        self.Labelframe2.configure(width=120)

        self.btn_enable = Button(self.Labelframe2)
        self.btn_enable.place(relx=0.08, rely=0.53, height=22, width=55)
        self.btn_enable.configure(activebackground="#d9d9d9")
        self.btn_enable.configure(activeforeground="#000000")
        self.btn_enable.configure(background=_bgcolor)
        self.btn_enable.configure(command=rbgui1_support.do_enable)
        self.btn_enable.configure(disabledforeground="#a3a3a3")
        self.btn_enable.configure(foreground="#000000")
        self.btn_enable.configure(highlightbackground="#d9d9d9")
        self.btn_enable.configure(highlightcolor="black")
        self.btn_enable.configure(pady="0")
        self.btn_enable.configure(state=DISABLED)
        self.btn_enable.configure(text='''Enable''')

        self.btn_reset = Button(self.Labelframe2)
        self.btn_reset.place(relx=0.08, rely=0.2, height=22, width=55)
        self.btn_reset.configure(activebackground="#d9d9d9")
        self.btn_reset.configure(activeforeground="#000000")
        self.btn_reset.configure(background=_bgcolor)
        self.btn_reset.configure(command=rbgui1_support.do_reset)
        self.btn_reset.configure(disabledforeground="#a3a3a3")
        self.btn_reset.configure(foreground="#000000")
        self.btn_reset.configure(highlightbackground="#d9d9d9")
        self.btn_reset.configure(highlightcolor="black")
        self.btn_reset.configure(pady="0")
        self.btn_reset.configure(text='''Reset''')

        self.entry_reset = Entry(self.Labelframe2)
        self.entry_reset.place(relx=0.67, rely=0.2, relheight=0.25, relwidth=0.2)

        self.entry_reset.configure(background="white")
        self.entry_reset.configure(disabledforeground="#a3a3a3")
        self.entry_reset.configure(font="TkFixedFont")
        self.entry_reset.configure(foreground="#000000")
        self.entry_reset.configure(highlightbackground="#d9d9d9")
        self.entry_reset.configure(highlightcolor="black")
        self.entry_reset.configure(insertbackground="black")
        self.entry_reset.configure(selectbackground="#c4c4c4")
        self.entry_reset.configure(selectforeground="black")

        self.entry_enable = Entry(self.Labelframe2)
        self.entry_enable.place(relx=0.67, rely=0.53, relheight=0.25
                , relwidth=0.2)
        self.entry_enable.configure(background="white")
        self.entry_enable.configure(disabledforeground="#a3a3a3")
        self.entry_enable.configure(font="TkFixedFont")
        self.entry_enable.configure(foreground="#000000")
        self.entry_enable.configure(highlightbackground="#d9d9d9")
        self.entry_enable.configure(highlightcolor="black")
        self.entry_enable.configure(insertbackground="black")
        self.entry_enable.configure(selectbackground="#c4c4c4")
        self.entry_enable.configure(selectforeground="black")

        self.Labelframe1 = LabelFrame(master)
        self.Labelframe1.place(relx=0.01, rely=0.76, relheight=0.2
                , relwidth=0.97)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Info''')
        self.Labelframe1.configure(background=_bgcolor)
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")
        self.Labelframe1.configure(width=680)

        self.entry_version = Entry(self.Labelframe1)
        self.entry_version.place(relx=0.01, rely=0.47, relheight=0.35
                , relwidth=0.31)
        self.entry_version.configure(background="white")
        self.entry_version.configure(disabledforeground="#a3a3a3")
        self.entry_version.configure(font="TkFixedFont")
        self.entry_version.configure(foreground="#000000")
        self.entry_version.configure(highlightbackground="#d9d9d9")
        self.entry_version.configure(highlightcolor="black")
        self.entry_version.configure(insertbackground="black")
        self.entry_version.configure(selectbackground="#c4c4c4")
        self.entry_version.configure(selectforeground="black")
        self.entry_version.configure(textvariable=rbgui1_support.wvar.gui_version)

        self.entry_counters = Entry(self.Labelframe1)
        self.entry_counters.place(relx=0.34, rely=0.47, relheight=0.35
                , relwidth=0.33)
        self.entry_counters.configure(background="white")
        self.entry_counters.configure(disabledforeground="#a3a3a3")
        self.entry_counters.configure(font="TkFixedFont")
        self.entry_counters.configure(foreground="#000000")
        self.entry_counters.configure(highlightbackground="#d9d9d9")
        self.entry_counters.configure(highlightcolor="black")
        self.entry_counters.configure(insertbackground="black")
        self.entry_counters.configure(justify=RIGHT)
        self.entry_counters.configure(selectbackground="#c4c4c4")
        self.entry_counters.configure(selectforeground="black")
        self.entry_counters.configure(textvariable=rbgui1_support.wvar.gui_counters)

        self.Entry11 = Entry(self.Labelframe1)
        self.Entry11.place(relx=0.68, rely=0.47, relheight=0.35, relwidth=0.27)
        self.Entry11.configure(background="white")
        self.Entry11.configure(disabledforeground="#a3a3a3")
        self.Entry11.configure(font="TkFixedFont")
        self.Entry11.configure(foreground="#000000")
        self.Entry11.configure(highlightbackground="#d9d9d9")
        self.Entry11.configure(highlightcolor="black")
        self.Entry11.configure(insertbackground="black")
        self.Entry11.configure(selectbackground="#c4c4c4")
        self.Entry11.configure(selectforeground="black")
        self.Entry11.configure(textvariable=rbgui1_support.wvar.gui_timers)

        self.Label8 = Label(self.Labelframe1)
        self.Label8.place(relx=0.06, rely=0.13, height=19, width=61)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(activeforeground="black")
        self.Label8.configure(background=_bgcolor)
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(highlightbackground="#d9d9d9")
        self.Label8.configure(highlightcolor="black")
        self.Label8.configure(text='''Version''')

        self.Label9 = Label(self.Labelframe1)
        self.Label9.place(relx=0.34, rely=0.13, height=19, width=108)
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(activeforeground="black")
        self.Label9.configure(background=_bgcolor)
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(highlightbackground="#d9d9d9")
        self.Label9.configure(highlightcolor="black")
        self.Label9.configure(text='''Process counters''')

        self.Label10 = Label(self.Labelframe1)
        self.Label10.place(relx=0.68, rely=0.13, height=19, width=101)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(activeforeground="black")
        self.Label10.configure(background=_bgcolor)
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(highlightbackground="#d9d9d9")
        self.Label10.configure(highlightcolor="black")
        self.Label10.configure(text='''Process times''')






if __name__ == '__main__':
    vp_start_gui()



